### ISSUE TITLE
Add carousel section for User Reviews

### ISSUE THREAD

**Issue by goyal-Dushi** [goyal-Dushi/react-coverpage-template#1]
Use minimal external lib (if required) and make a carousel of user reviews with bootstrap or custom CSS styles. You can refer to other websites for styles in which user reviews are showed.

**Comment by rkoleci** [comment]
Can you assign this to me ?

**Comment by goyal-Dushi** [comment]
> Can you assign this to me ?

sure @rkoleci

**Comment by rkoleci** [comment]
I will work on this

**Comment by rkoleci** [comment]
Create a PR.
  https://github.com/rkoleci/react-coverpage-template/pull/new/carousel

Edit the src img links to your preferred images.

Thnx

**Comment by goyal-Dushi** [comment]
> Create a PR. https://github.com/rkoleci/react-coverpage-template/pull/new/carousel
> 
> Edit the src img links to your preferred images.
> 
> Thnx

Hey @rkoleci , can you create a preview deployment for your PR so that I could view the changes in the browser. Also, it seems like you just included the carousel component. What I really want is a user reviews section within a carousel ! LIke, refer to product-based websites where they have their user reviews. Eg. upgrad has a student review section for each of its courses.

**Comment by rkoleci** [comment]
> > Create a PR. https://github.com/rkoleci/react-coverpage-template/pull/new/carousel
> > Edit the src img links to your preferred images.
> > Thnx
> 
> Hey @rkoleci , can you create a preview deployment for your PR so that I could view the changes in the browser. Also, it seems like you just included the carousel component. What I really want is a user reviews section within a carousel ! LIke, refer to product-based websites where they have their user reviews. Eg. upgrad has a student review section for each of its courses.

OKay, I will create the user review section. no problemo

**Comment by rkoleci** [comment]
Created a boostrap carousel for user reviews based on a design i found online.

**Comment by goyal-Dushi** [comment]
> Created a boostrap carousel for user reviews based on a design i found online.
> 
> Check it here: https://drive.google.com/file/d/1M4Hw58sfqs4wsjOCcUjjjXvBxVAXVC5R/view?usp=sharing

I want it in a Card format, like review cards, and for the design and color, make sure that it goes with the colors used in the website (coverpage-template). Also apart from dummy content, do include dummy images for users. And for styling , be as creative as you want to be :) .

**Comment by rkoleci** [comment]
I have done some changes. Check it out.

**Comment by goyal-Dushi** [comment]
> I have done some changes. Check it out.

Hey @rkoleci, I have seen the changes and they look fine. But there are changes I want you to make:

1) **Responsiveness of cards**:  on widths below 425px, mobile widths, the card images flow out of the card which seems odd.
2) **Font sizes used inside the cards**:  the text inside cards make them more elongated while viewing in mobile widths, thus it requires scrolling down to view complete card content. So please fix font-sized for different responsive layouts.
3) **Change heading**: Change heading from `Read what our past patients said about our medical center.`   to `Our customer reviews`. 
4) **Indicators**:  Please include indicators for the carousel, give them some different design and color from default bootstrap designs
5) Also include the `Reviews` nav link in the navbar. so that on clicking it, it takes us to this particular section.
6) Change the text color for people's names and designation from `red` to some shade of `blue`. I believe it will look better
7) Also, when the card switches, so due to margin/padding at the bottom and based on card content,the section below tends to move down and up. So if you could do such that even though card switches, it should not affect other sections to move up and down.

**Comment by rkoleci** [comment]
Made all changes, apart from 4. 
Bootrap seems to have a problem with indicators in React lib.

Merge it if you like it please.
:)

**Comment by goyal-Dushi** [comment]
> Made all changes, apart from 4. Bootrap seems to have a problem with indicators in React lib.
> 
> Merge it if you like it please. :)

Hey @rkoleci, the UI looks good. There are some code related changes I need you to make:
1) Remove assets dir from src folder and move the images to the assets folder of public dir, `public/assets/images/`.
2) Change the img format from `jpg` to webp`. 
3) Remove the data within the Carousel.js file into a separate json file. ie. `src/data/userReviews.json/`.
4) Rename  `Carousel.js` file to `UserReviews.module.js` file. and similarly its CSS file as 'userReviews.css`.

**Comment by rkoleci** [comment]
Checkit.

**Comment by goyal-Dushi** [comment]
> Checkit.

Hey @rkoleci, everything looks good, but you have increased both top & bottom padding for `carousel-container .item` , instead, I mentioned I wanted **less** spacing between heading and carousel and **more** spacing between `UserReviews` and `KeepInTouch` section.

**Comment by rkoleci** [comment]
My bad. Check it

**Comment by goyal-Dushi** [comment]
> My bad. Check it

Looks good :+1:
